### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by GavJenks**
Adding missing mobs as a possible means of addressing spawning problems with ones that happen to also be missing from the config. Should probably be done anyway regardless.

### CODE REVIEW

**Comment by rourke750** [comment]
for slime, endermen, and lavaslime they dont need to be added.  I believe they are rare enough to not need to be watched by mustercull.

**Comment by ttk2** [comment]
His theory is that mustercull is culling them because they are not on the
list.

**Comment by rourke750** [comment]
Well that isn't true. It ignores mobs that aren't on the list.

**Comment by ttk2** [comment]
meh its worth trying. Is there anything wrong with these rules? otherwise
onto Civtest it goes

**Comment by ttk2** [comment]
on civtest

**Comment by rourke750** [comment]
Well some farms will become more inefficient at the best.

**Comment by ttk2** [comment]
hmm how so?

**Comment by rourke750** [comment]
Well endermen will suffer a culling and spawning issue when there wasn't one before.  Ghasts will start being culled where before they werent really affected.
It might actually be worth it to test how this affects spawning.

**Comment by jjj5311** [comment]
If there are no enderman spawning in the main end island how can it be
worse?

I have not seen enderman in the overworld in weeks

**Comment by ttk2** [comment]
we should be wary of introducing errors we might have to deal with later.

**Comment by GavJenks** [comment]
Rourke, last time we discussed this, your evidence for "no it ignores things not on the list" was a link to a java class that merely linked to a method from another class. You have to follow it to see where the default info was coming from (whether filled in or ignored, depending on if that method returned nulls or defaults for missing entries), and nobody followed up on how that code pathway works.

When I followed the methods around myself for hours, I was still unable to figure out for sure whether it was ignored or whether it filled in default values. Because it's a big bowl of spaghetti.

So I still maintain that it is a distinct possibility that things not on the list are indeed not being ignored, but either being given some other default values OR are flowing into some bug that only inconsistently screws them up through that path of code.

I'm not sure what side effects you would be worrying about. When have 5 ghasts ever been in 100 meter radius of one another here? Maybe endermen, but if worried, just make it limit 30 or something. The goal has much less to do with the values themselves, but rather preventing the code from flowing into the dark mystery closet of default behavior where bugs etc. might lie (since all the buggy mobs share this one common feature)

**Comment by rourke750** [comment]
I'm just going to leave this here: https://github.com/Civcraft/MusterCull/blob/master/MusterCull/src/com/untamedears/mustercull/MusterCull.java#L128  which also has the java docs which says specifically will return null if none is specified.  Then again here: https://github.com/Civcraft/MusterCull/blob/master/MusterCull/src/com/untamedears/mustercull/EntityListener.java#L50 it ignores trying to cancel the spawn if it is not defined.

**Comment by rourke750** [comment]
> When have 5 ghasts ever been in 100 meter radius of one another here?

You haven't seem some farms.

**Comment by erocs** [comment]
> preventing the code from flowing into the dark mystery closet of default behavior where bugs etc. might lie

If it's that buggy it should be rewritten.

**Comment by GavJenks** [comment]
Rourke: I know, I also saw the documentation that that's what it's SUPPOSED to do. But obviously there's some sort of a bug involved, and you can't just trust documentation when you're trying to find a bug, because the point is it isn't working as the programmer intended.

"You haven't seen some farms" Okay, change to higher numbers then, I just threw down some.

"If it's that buggy it should be rewritten" It may only be, like, one bug. But yes it is still pretty badly written. Redoing it is probably a good idea. Especially if it could be redone to completely control spawning instead of reacting to it.

**Comment by erocs** [comment]
Also, if there is no limit configured for an entity during the current cull type, MusterCull doesn't return the entity, so it wouldn't be culled via the standard damage culling (this is not hard-cap culling). https://github.com/Civcraft/MusterCull/blob/38cdb6735/MusterCull/src/com/untamedears/mustercull/MusterCull.java#L337

This does mean that unconfigured entities will never be gradually culled but still add to the overall entity count. This could contribute to hitting the hard-cap limit more often, say if 2500 endermen are sitting there not culled there would only be room for 2500 other LivingEntities. The hard-cap laborer would in-fact factor these unconfigured endermen into the counts for priority culling.

I'd recommend always having a configuration entry for all possible mob types for all culling types in order to include them in standard culling.

**Comment by dbear20** [comment]
You sure these values were added to the civtest config? I currently have a lot of ghasts held in a relatively small area and none of them had been culled. I had done the same thing with enderman and none of them were culled either.

**Comment by ttk2** [comment]
it is on Civtest

**Comment by GavJenks** [comment]
That's utterly bizarre. I am confirming this with all of those mobs, endermen, slimes, ghasts.... it's neither preventing my egg usage nor culling them later if they get in range of each other, both unlike sheep.

It is definitely acting as if that update were simply not uploaded on the server at all. (This is totally aside from it fixing natural spawning or not -- regardless of that it should certainly be culling crowds)

**Comment by ttk2** [comment]
oh build is not merged, merging .

**Comment by ttk2** [comment]
this was a failure, reverting the merge.

**Pull request merged**
