### PR TITLE
Adding ghasts to the config.yml

### PR DESCRIPTION
**Pull request by BlackXnt**
People aren't going to like this but it has to be done. I walked near a farm with over 15 ghasts today that were just waiting for hours for a player to come kill them. @ttk2 I tested MusterCull on cvitest and the changes to the /cull command and to the range are working.

### CODE REVIEW

**Comment by ttk2** [comment]
agreed, its a very generous limit too.

**Comment by ProgrammerDan** [comment]
Note, the farm I've afk'd hasn't had a single ghast since this patch; about 99% certain there is no other farm within 144 blocks in any direction. Any chance this is reacting badly since ghast spawn is already a chance event against pigment spawn?

**Comment by ttk2** [comment]
If it is no one knows why. How has everyone else's spawning been?

**Comment by ProgrammerDan** [comment]
Just did a 12 hour AFK session, doublechecked with the only other person with access to the farm, confirmed no ghasts. Skeleton spawn was zilch in the same time as well. Snitches were empty, so no outside party was swiping, literally only myself and this other player are on the snitch groups.

I'll begin looking in to why this might be the case, but I'd recommend reversing this commit if you've got any other reports of low/no ghast spawns.

**Comment by ttk2** [comment]
that's bizzare, we can't just reverse the commit, no one will figure it out
in that case, we have to point people at it until its fixed. Bummer though.

**Comment by jjj5311** [comment]
I can confirm no ghosts at my farm either

**Comment by ttk2** [comment]
2015-06-12 08:24:27 [INFO] [MusterCull] Culling GHAST using DAMAGE;
limit=8 range=144
2015-06-12 08:24:27 [INFO] [MusterCull] Culling GHAST using SPAWN;
limit=8 range=144
2015-06-13 08:24:28 [INFO] [MusterCull] Culling GHAST using DAMAGE;
limit=8 range=144
2015-06-13 08:24:28 [INFO] [MusterCull] Culling GHAST using SPAWN;
limit=8 range=144

this looks like somthing else is up. Not enough spawn instances to
really matter that they are being culled.

**Comment by BlackXnt** [comment]
This is weird. I will look into it today.

**Comment by ProgrammerDan** [comment]
Thanks BlackXnt, let me know if there's anything I can do to assist
(construct something on civtest, etc.).

**Comment by BlackXnt** [comment]
@ttk2 What you brought here is the only time the word "GHAST" is being mentioned in the log?

**Comment by ttk2** [comment]
Well there where some other entries. Mostly ghast years. But as for
cullings yes these where the only events as of this morning in a recent
time frame.

**Pull request merged**
