### PR TITLE
Better compatibility with 1.8.3

### PR DESCRIPTION
**Pull request by dbear20**
Added if statement to prevent the plugin from breaking due to spigot filtering out large getentites ranges by capping how high the range can be set in the config. I only edited lines 198-202, i'm not sure why its saying i edited other lines.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Change looks safe and straightforward, assuming the technique used to grab the logger is a-ok.

**Comment by ttk2** [comment]
this looks like a good idea.

**Comment by rourke750** [comment]
please build this

**Comment by rourke750** [comment]
ok to test

**Pull request merged**
