### PR TITLE
Boats and a new log file.

### PR DESCRIPTION
**Pull request by BlackXnt**
I added an option to cull vehicles using the cull command. If you want to cull all the empty boats just do /cull boat. You can also do /cull boat Range PlayerName to cull boats near a specific player.
In addition with these changes MusterCull will send all of his debug messages to a file that can be found in his data folder. This should allow us to more easily check if anything is going wrong.
@ttk2 Can you ask in the changelog / make a thred on discourse and try getting players to report any problems with MusterCull?
If nothing significant is reported and nothing pops up in the logs I am just going to work on the new features rourke suggested.

### CODE REVIEW

**Comment by ttk2** [comment]
Nice, changes here. 

Most of the current issues are endemic of the small culling radius in the config required by the way Spigot changed  to limiting get entities calls.

**Comment by BlackXnt** [comment]
@ttk2 This will allow you to set any range you want.

**Comment by ttk2** [comment]
Yay! How does it get around the issue? Search pattern of limited calls?

**Comment by BlackXnt** [comment]
This is just scanning through all the entities and making a new list with the entities in range. this is the solution @ProgrammerDan brought here: https://github.com/Civcraft/MusterCull/issues/29. I didnt find any other effective way to bypass it. We should try this first and see if this is causing any problems.

**Comment by ttk2** [comment]
ok then, going to have someone look this over, then we can move it into testing pronto. 


The cull limit needs to be set to view distance again in the config.

**Comment by ttk2** [comment]
ok going on Civtest.

**Pull request merged**
