### PR TITLE
MasterMerge

### PR DESCRIPTION
**Pull request by BlackXnt**
I am aware there are still edge cases that need to be handled(like sheeps and withers) but I already finished most of the basics features and I decided it will be a good idea to let someone review it before keep going. I have tested this version on my local server and merging seems to be working, but it is hard testing MusterCull on a testing server with only 1 player online. 

This is an example of how to add an entity to the config:
- type: CREEPER
  culling: MERGE
  limit: 3
  range: 144
  spawnDelay: 5
  multiplier: 0.5

A creeper will only spawn after 5(spawnDelay) creepers attempted to spawn at the same area( range - 144 blocks). The creeper will have the combined drops of all the other creepers that attempted to spawn * the multiplier(in this case 1 + 4*0.5 = 3). Once there are 3(limit) creepers at the same area all the creepers that attempt to spawn will be merged into the existing creepers.

Its really late for me so I will explain more about the code tomorrow I just wanted to get this pull up in the meantime. (Just to be clear I didn't change the name of the plugin I just thought this is a cool title for the pull)

### CODE REVIEW

**Comment by ttk2** [comment]
nice, do you want me to make a testing build and put it up?

**Comment by BlackXnt** [comment]
Yes, I will add entities to the config in game.

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
ok its on Civtest, go for it.

**Comment by BlackXnt** [comment]
Are you getting any stack traces?

**Comment by ttk2** [comment]
2015-06-20 10:13:10 [ERROR] Error occurred while enabling MusterCull v1.4.3
(Is it up to date?)
java.lang.IllegalArgumentException: No enum constant
org.bukkit.entity.EntityType.CAVESPIDER
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_45-internal]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:1)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
com.untamedears.mustercull.Configuration.load(Configuration.java:213) ~[?:?]
        at
com.untamedears.mustercull.MusterCull.onEnable(MusterCull.java:96) ~[?:?]
        at
org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]


this is the only one so far

**Comment by BlackXnt** [comment]
Did you update the config too?

**Comment by ttk2** [comment]
now i did

**Comment by BlackXnt** [comment]
can you update the jar on civtest with this commit?

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
its up

**Comment by ttk2** [comment]
hows this going?

**Comment by BlackXnt** [comment]
Great! I have tested everything I could think of and only found one bug. I will fix it on monday + clean the code a bit and let someone review it. Also can I get the logs of MusterCull from civtest?

**Comment by ttk2** [comment]
https://mega.nz/#!N9NjDSbD!yjwELiLs0hCjTGNEJB4rX6J5Qti2Mt8hsD-mF1J6_vs

here are the logs.

**Comment by ttk2** [comment]
so whats up with this?

**Comment by BlackXnt** [comment]
I still need to clean the code and add a new config option. I didn't have time to even open Eclipse since saturday. I hope I will finish it today.

**Comment by ttk2** [comment]
Sounds great keep me posted.

**Comment by BlackXnt** [comment]
In addition to the code cleanup I added a new config option to limit the multiplier of each entity so players can't "afk a mob" and get a ridiculous amount of drops / they still have to make their farm efficient and kill the mobs ASAP. Support for sheeps was also added - the multiplier will affect the amount of wool the sheep drops when sheared by a player. I only have to fix one more thing before we can go live with the changes(adding limits in-game and saving them on server restart).

**Comment by ttk2** [comment]
nice, just let me know when to upload stuff to Civtest.

**Comment by BlackXnt** [comment]
You can put it on civtest now. I will deal with adding limits in-game later - its not high priority at all.

**Comment by BlackXnt** [comment]
Update the config file on civtest too.

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
on civtest

**Comment by BlackXnt** [comment]
Are you getting stacks? I dont see a single mob on civtest.

**Comment by ttk2** [comment]
nope all is quiet, maybe someone changed the gamemode?

**Comment by BlackXnt** [comment]
I dont think that's the case. Can I get the logs of MusterCull? Especially the ones from when the server restart.

**Comment by ttk2** [comment]
looks like the log file did not get updated right, downloaded a new one, try now.

**Comment by BlackXnt** [comment]
Still no mobs.

**Comment by ttk2** [comment]
I think somthing must be up with mustercull, not a single message from it once it was enabled.

**Comment by ttk2** [comment]
or not up with mustercull maybe no mobs=no messages?

**Comment by BlackXnt** [comment]
This is really weird. I am running the same version on my local server and it is working just fine. Can you post all the logs from when it was enabled? maybe something is wrong with the config.

**Comment by ttk2** [comment]
2015-06-25 07:44:09 [INFO] [MusterCull] Enabling MusterCull v1.4.3
2015-06-25 07:44:09 [INFO] [MusterCull] Warning: damage is <= 0, possibly wasting cpu cycles.
2015-06-25 07:44:09 [INFO] [MusterCull] Warning: damage_chance is <= 0, possibly wasting cpu cycles.
2015-06-25 07:44:09 [INFO] [MusterCull] Warning: damage_count is <= 0, possibly wasting cpu cycles.
2015-06-25 07:44:09 [INFO] [MusterCull] MusterCull will damage something every 0 ticks.
2015-06-25 07:44:09 [INFO] [MusterCull] Warning: ticks_between_damage is < 20, probably won't run that fast.
2015-06-25 07:44:09 [INFO] [MusterCull] Warning: merge_count is <= 0, possibly wasting cpu cycles.
2015-06-25 07:44:09 [INFO] [MusterCull] MusterCull will merge something every 0 ticks.
2015-06-25 07:44:09 [INFO] [MusterCull] Warning: ticks_between_merge is < 20, probably won't run that fast.
2015-06-25 07:44:09 [INFO] [MusterCull] Monster cull: Up to 30 mobs per run, aggression is 0 to 0.
2015-06-25 07:44:09 [INFO] [MusterCull] Monster cull: Up to 30 mobs per run, aggression is 0 to 0.
2015-06-25 07:44:09 [INFO] [MusterCull] Monster cull: Up to 0 mobs per run, aggression is 0 to 0.
2015-06-25 07:44:09 [INFO] [MusterCull] MusterCull will kill something every 0 ticks.
2015-06-25 07:44:09 [WARN] [MusterCull] ticks_between_hard_cap is < 200, ignoring this and setting to 200.
2015-06-25 07:44:09 [WARN] [MusterCull] hard_cap_culling_strategy not an allowed value (needs RANDOM or PRIORITY - has null.


thats it

**Comment by BlackXnt** [comment]
It doesnt find the config file. Did you put the config.yml from this pull in the mustercull's data folder?

**Comment by ttk2** [comment]
found it I was downloading the plugin.yml instead of the  config, should
work now.

**Comment by BlackXnt** [comment]
Great! I need to change the default settings so it won't just completely remove all the mobs. I am going to do the final round of testing today. I suggest we go online with the changes only with zombie pigman at the start and see how it affects portal farms before applying the changes to the rest of the mobs.

**Comment by ttk2** [comment]
Ok then. Just let me know when its ready to stage.

**Comment by BlackXnt** [comment]
Are you getting stacks now?

**Comment by ttk2** [comment]
nope no stacks.

**Comment by ttk2** [comment]
just go this one on restart. 

2015-06-25 19:12:35 [ERROR] Error occurred while enabling MusterCull v1.4.3 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.CAVESPIDER
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_45-internal]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.untamedears.mustercull.configurations.Configuration.load(Configuration.java:217) ~[?:?]
        at com.untamedears.mustercull.MusterCull.onEnable(MusterCull.java:107) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by BlackXnt** [comment]
You are not running the updated config. In the config of this pull I it is CAVE_SPIDER not CAVESPIDER.

**Comment by ttk2** [comment]
corrected, sorry.

**Comment by BlackXnt** [comment]
Ok I finished testing, I am not going to find any new bugs on a testing server. I have added zombie pigs  to the config of this pull, this is ready to go online.

**Comment by ttk2** [comment]
ok then, I will set it up for tomorrow morning.

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
ok to test

**Comment by BlackXnt** [comment]
Make sure you get the right config :D

**Comment by ttk2** [comment]
I just did, its all on civtest for final checking, also please write a changelog blurb about what exactly this is and how players will be affected by it.

**Comment by BlackXnt** [comment]
I will make a post on the forum today/tomorrow morning.

**Comment by ttk2** [comment]
well its going online tomorrow morning, so I would like to be able to set up the link tonight when I setup the changelog the bot will psot.

**Comment by BlackXnt** [comment]
It will be hard it's 2am for me. I will try to get it for today.

**Comment by ttk2** [comment]
oh, then sleep, send it to me when you wake up.

**Comment by BlackXnt** [comment]
One more important thing I forgot to say. You need to turn off the multiplier for zombie pigman humbug.

**Comment by BlackXnt** [comment]
@ttk2  https://forum.civcraft.co/t/open-for-testing-mustercull/551

**Comment by ttk2** [comment]
yay, looks good to me.

**Comment by ttk2** [comment]
will merge if it does not explode tomorrow morning, remind me to. Well  I guess if its live it should get merged, here goes nothing.

**Comment by BlackXnt** [comment]
I hope you remembered to set the multiplier in humbug to be 1.

**Comment by ttk2** [comment]
I did

**Pull request merged**
