### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by dbear20**
Changed range for are mobs to 203 and cut farmed mob limits in half.

### CODE REVIEW

**Comment by ttk2** [comment]
thank you.

**Comment by ttk2** [comment]
wait what about spawner mobs?

**Comment by dbear20** [comment]
I wasn't sure if you wanted all mobs cut in half or just the ones that tend to be a problem. Or are spawner mobs more prevalent than I'm imagining?

**Comment by ttk2** [comment]
much, spiders are right behind pigmen for lag.

**Pull request merged**
