### PR TITLE
ArmorStand Check for Issue #28

### PR DESCRIPTION
**Pull request by IslandProdigy**

### CODE REVIEW

**Comment by ttk2** [comment]
is this the first pull for this issue? I remember seeing another, also the
pigman range needs to be fixed too before I can use this config.

**Comment by IslandProdigy** [comment]
I don't see any other pull requests similar to this one.

**Comment by ttk2** [comment]
needs a code review and then testing then.

**Comment by rourke750** [comment]
Code is fine, we can get a testing jar from the bot if you want it.

**Comment by rourke750** [comment]
ok to test

**Comment by ttk2** [comment]
so this just removes armor stands from things that can be culled?

**Comment by rourke750** [comment]
Yes.

**Comment by ttk2** [comment]
Island, you still here? Would you be willing to put your code contribution under BSD 3 clause?

**Comment by IslandProdigy** [comment]
Yes.

**Pull request merged**
