### PR TITLE
update config.yml

### PR DESCRIPTION
**Pull request by BlackXnt**
I added more mobs. I am still trying to figure out a bug with animals so they are not on this config.

### CODE REVIEW

**Comment by ttk2** [comment]
so no merge yet? Do you want me to test it?

**Comment by BlackXnt** [comment]
No it's fine you can throw this into civcraft.

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
so then what does this do exactly right now?

**Comment by BlackXnt** [comment]
Just add more mobs that MusterCull will attempt to merge(it was only working on pigmen so far). I didn't change anything in the code, only edited config file.

**Comment by ProgrammerDan** [comment]
Do we have explicit confirmation that merging is working as expected on Civcraft?

I haven't tried AFK'ing my gold farm in a week, so I can't attest one way or the other.

**Comment by ttk2** [comment]
there seemed to be some confirmation in the testing thread on discourse, but  I am not sure how explicit that was

**Comment by BlackXnt** [comment]
Yes it does work as expected. Me and Max tested it on civcraft. The drops from portal farms are still low tho. Mostly because of the change to mob AI - The pigmen get stuck on the portals and it takes a long time until they die. I think the best soulation here will be spawning the pigmen a block away from the portals.

**Comment by ttk2** [comment]
I have re-enabled mob AI for tomorrow morning, you want this merged and online tomorrow morning? Do I need to update the config?

**Comment by BlackXnt** [comment]
Yes please. I hope the mob AI isn't going to drop the tps significantly.

**Comment by rourke750** [comment]
@ttk2 On my explorations I figured out how to manually turn off and on mob ai per entity.  If you have any ideas for that I'm all ears.

**Comment by ttk2** [comment]
lets see how it works out with stuff turned on, anyways merging.

**Comment by ttk2** [comment]
this is online now.

**Pull request merged**
